### ISSUE TITLE
Downloadable list of QR code for equipment

### ISSUE THREAD

**Issue by Gudfaren** [roarengen/equiplib#167]

**Comment by Joonsey** [comment]
![image](https://github.com/roarengen/equiplib/assets/59510166/e7b217cf-e2eb-4409-8dac-1981f194ea7a)
Implemented solution for the chip at the bottom, this is now a dynamic component made with the intent of being re-destributable and re-usable.

Need feedback on how specifically this UX / user flow should be.

**Comment by Joonsey** [comment]
the icon in the chip is the actual qr-code of the item as well.

**Comment by Joonsey** [comment]
should be fixed in d8a12483437e8e6ddcd7e05868397d8bd6e60d57

reopen this issue if unsatisfactory
