### ISSUE TITLE
Sette opp VM 

### ISSUE THREAD

**Issue by roarengen** [roarengen/equiplib#6]
Daemon, WebInstance og NginX, SQL server

**Comment by Joonsey** [comment]
NOTE: #30 should be completed before this

**Comment by Joonsey** [comment]
- [x] make users and groups
- [x] firewall
- [x] setup nginx 
- [x] configure nginx
- [x] start gunicorn instance
- [x] make and run systemd service for gunicorn instance
- [x] migrate repo to a public repo on server


# INFO

Repo is in /opt/equiplib

nginx config is in default nginx conf directory;
`/etc/nginx/sites-available/equiplib`
with a symlink to: /etc/nginx/sites-enabled

systemctl service is in: /etc/systemd/system/equiplibapi.service
